{% set name = "dmri-amico" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 6e18066fd8b80c0aa754c14c9296b4bbce9092a156e940a7f0176723e112cba1

  # allow separate libraries for lapack / blas, rather than
  # assuming a single library, i.e.  openblas, for both. See
  # https://github.com/daducci/AMICO/pull/179
  patches:
    - setup.py.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
    - cython                              # [build_platform != target_platform]
  host:
    - cython
    - libblas
    - liblapack
    - python
    - pip
    - setuptools
    - spams-cython
  run:
    - dipy
    - dmri-dicelib
    - h5py >=3
    - python
    - numpy
    - scipy
    - threadpoolctl

test:
  imports:
    - amico
  commands:
    - python -c "import amico; amico.setup()"

about:
  home: https://pypi.org/project/dmri-amico/
  license: LicenseRef-DICE-lab
  license_file: LICENSE
  summary: Implementation of the linear framework for Accelerated Microstructure Imaging via Convex Optimization (AMICO) described in Daducci, Alessandro, et al. 2015
  dev_url: https://github.com/daducci/AMICO/

extra:
  recipe-maintainers:
    - daducci
    - nightwnvol
    - pauldmccarthy
